project_name: mr
builds:
  - env: [CGO_ENABLED=0]
    main: ./cmd
    ldflags:
      - -s -w -X version.Version={{.Version}} -X version.Goversion={{.Commit}} -X version.Dirty={{.Date}}
    goos:
      - linux
    goarch:
      - amd64
      - arm64

snapshot:
  name_template: "{{ .ShortCommit}}"

release:
  # Repo in which the release will be created.
  # Default is extracted from the origin remote URL or empty if its private hosted.
  # github:
  #   owner: user
  #   name: repo

  # If set to true, will not auto-publish the release.
  # Default is false.
  draft: false

  # If set, will create a release discussion in the category specified.
  #
  # Warning: do not use categories in the 'Announcement' format.
  #  Check https://github.com/goreleaser/goreleaser/issues/2304 for more info.
  #
  # Default is empty.
  #discussion_category_name: 

  # If set to auto, will mark the release as not ready for production
  # in case there is an indicator for this in the tag e.g. v1.0.0-rc1
  # If set to true, will mark the release as not ready for production.
  # Default is false.
  #prerelease: false

  # What to do with the release notes in case there the release already exists.
  #
  # Valid options are:
  # - `keep-existing`: keep the existing notes
  # - `append`: append the current release notes to the existing notes
  # - `prepend`: prepend the current release notes to the existing notes
  # - `replace`: replace existing notes
  #
  # Default is `keep-existing`.
  mode: replace

  # Header template for the release body.
  # Defaults to empty.
  header: |
    Welcome to this release!

  # Footer template for the release body.
  # Defaults to empty.
  footer: |
    ## Thanks!

    Those were the changes on {{ .Version }}!

  # You can change the name of the release.
  # Default is `{{.Tag}}` on OSS and `{{.PrefixedTag}}` on Pro.
  name_template: "v{{.Version}}"

  # You can disable this pipe in order to not create the release on any SCM.
  # Keep in mind that this might also break things that depens on the release URL, for instance, homebrew taps.
  #
  # Defaults to false.
  disable: false