name: Release

on:
  push:
    tags:
      - "v*"

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  BINARY: mr

jobs:
  release:
    name: Cross build for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            cross: false
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            cross: false
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            cross: true
          - os: ubuntu-latest
            target: aarch64-unknown-linux-musl
            cross: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.78
          default: true
      
      # Native build
      - name: Install target
        if: matrix.cross == false 
        run: rustup target add ${{ matrix.target }}
      - name: Build release
        if: matrix.cross == false 
        run: cargo build --release --target ${{ matrix.target }}

      # Cross build
      - name: Install cross
        if: matrix.cross
        run: cargo install --version 0.2.5 cross
      - name: Build release
        if: matrix.cross
        run: cross build --release --target ${{ matrix.target }} 

      - name: Run UPX
        # Upx may not support some platforms. Ignore the errors
        continue-on-error: true
        if: matrix.os == 'ubuntu-latest' 
        uses: crazy-max/ghaction-upx@v1
        with:
          version: v4.0.2
          files: target/${{ matrix.target }}/release/${{ env.BINARY }}
          args: -q --best --lzma
      - uses: actions/upload-artifact@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: ${{ env.BINARY }}-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/${{ env.BINARY }}
      - name: Zip Release
        uses: TheDoctor0/zip-release@0.6.1
        with:
          type: zip
          filename: ${{ env.BINARY }}-${{ matrix.target }}.zip
          directory: target/${{ matrix.target }}/release/
          path: ${{ env.BINARY }}
      - name: Publish
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/${{ matrix.target }}/release/${{ env.BINARY }}-${{ matrix.target }}.zip
          generate_release_notes: true
          draft: true

  publish-crate:
    name: Publish to crates.io
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: release
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}
        run: cargo publish
